package:
  name: q2_srs
  version: 2021.4.0
source:
  path: ../

build:
    noarch: generic

extra:
  channels:
    - conda-forge
    - bioconda

requirements:

  build:
    - python=3.8
    - setuptools

  run:
    - python=3.8
    - qiime2 >=2021.4
    - q2-types
    - biom-format
    - pandas

about:
  home: https://github.com/vitorheidrich/q2-srs
  license: BSD-3-Clause
  license_family: BSD
